server:
  port: 8089
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/xfyl?serverTimezone=GMT%2b8&useSSL=false&characterEncoding=utf8&allowPublicKeyRetrieval=true&autoReconnect=true
    username: root
    password: 616627hj
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    druid:
      initial-size: 5
      min-idle: 1
      max-active: 20
  servlet:
    multipart:
      max-file-size: 20MB
      enabled: true
      max-request-size: 20MB

logging:
  level:
    com.trust.xfyl.dao: debug

mybatis:
  mapper-locations: mapper/*.xml
  type-aliases-package: com.trust.xfyl.entity
  mybatis-config-file: mybatis-config.xml
  configuration.map-underscore-to-camel-case: false


imageurl:
  uploadImgUrl: D:\home\app\uploadImg\


downloadurl:
  downloadImgUrl: D:\home\app\downloadImg\

aliyun:
  api:
    url: https://vision.console.aliyun.com/cn-shanghai/detail/imageprocess
    roleArn: acs:ram::1306143105217098:role/ramosstest
    policy: |
      {
        "Version": "1",
        "Statement": [
          {
            "Effect": "Allow",
            "Action": [
              "oss:PutObject",
              "oss:GetObject"
            ],
            "Resource": [
              "acs:oss:*:*:drt-oss-disk/src/*",
              "acs:oss:*:*:drt-oss-disk/dest/*"
            ]
          }
        ]
      }
    externalId: xfyl



swagger:
  basic:
    enable: true
    username: admin
    password: admin

