# 服务器配置
server:
  port: 8089

# Spring框架配置
spring:
  application:
    name: xfyl # 应用名称
  freemarker: # FreeMarker模板配置
    cache: false # 是否缓存
    charset: UTF-8 # 编码字符集
    suffix: .ftl # 模板后缀
    enabled: true # 是否启用
    content-type: text/html # 内容类型
    template-loader-path: classpath:/templates/,classpath:/static/ # 模板加载路径
  datasource:
    url: jdbc:mysql://localhost:3306/xfyl?serverTimezone=GMT%2b8&useSSL=false&characterEncoding=utf8&allowPublicKeyRetrieval=true&autoReconnect=true # 数据库连接URL
    username: xxxx
    password: xxxxxxx
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    druid:
      initial-size: 10 # 初始化连接池大小，类似minimum-idle
      min-idle: 10 # 最小空闲连接数
      max-active: 20 # 最大活跃连接数，类似maximum-pool-size
      test-on-borrow: true # 借用连接时进行测试
      validation-query: SELECT 1 # 测试查询语句
      connect-timeout: 30000 # 连接超时时间
  servlet: # Servlet配置
    multipart: # 多部分文件上传配置
      max-file-size: 20MB # 最大文件大小
      enabled: true # 是否启用
      max-request-size: 20MB # 最大请求大小url: jdbc:mysql://127.0.0.1:3306/xfyl?serverTimezone=GMT%2b8&useSSL=false&characterEncoding=utf8&allowPublicKeyRetrieval=true&autoReconnect=true # 数据库连接URL

# 日志配置
logging:
  level:
    com.trust.xfyl: debug # 日志级别

# MyBatis配置
mybatis:
  mapper-locations: mapper/*.xml # Mapper文件位置
  type-aliases-package: com.trust.xfyl.model # 类型别名包
  mybatis-config-file: mybatis-config.xml # MyBatis配置文件位置
  configuration.map-underscore-to-camel-case: false # 是否将下划线映射到驼峰命名
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
# 图片上传路径配置
imageurl:
  uploadImgUrl: D:\home\app\uploadImg\

# 文件下载路径配置
downloadurl:
  downloadImgUrl: D:\home\app\downloadImg\

# 阿里云配置
aliyun:
  api: # 阿里云API配置
    url: https://vision.console.aliyun.com/cn-shanghai/detail/imageprocess # API地址
    roleArn: acs:ram::xxxxxxxxxxxx:role/ramosstest # 角色ARN
    policy: | # 策略配置
      {
        "Version": "1",
        "Statement": [
          {
            "Effect": "Allow",
            "Action": [
              "oss:PutObject",
              "oss:GetObject"
            ],
            "Resource": [
              "acs:oss:*:*:drt-oss-disk/src/*",
              "acs:oss:*:*:drt-oss-disk/dest/*"
            ]
          }
        ]
      }
    externalId: xfyl # 外部ID

# Swagger配置
swagger:
  basic: # 基础配置
    enable: true # 是否启用
    username: admin # 用户名
    password: admin # 密码

# 聊天配置
chat:
  llm: # 语言模型配置
    timeout: 60 # 超时时间，单位：秒
  security: # 安全配置
    refererWhitelist: # 引用来源白名单
      - xxxxxx
      - xxxx
  app: # 应用配置
    openTrace: true # 是否开启追踪
    sessionMaxMessages: 50 # 对话记录最大数量
    sessionTtl: 2 # 对话缓存时间，单位：小时
  cache: # 缓存配置
    type: caffeine # 缓存类型
wechat:
  appId: xxxxxxxx
  appSecret: xxxxxxxxx
yskin:
  clientId: xxxxxx
  clientSecret: xxxxxxxxxx
