server:
  port: 8800
spring:
  datasource:
    url: jdbc:mysql://121.43.138.108:3306/xfyl?serverTimezone=GMT%2b8&useSSL=false&characterEncoding=utf8&allowPublicKeyRetrieval=true
    username: root
    password: Drt@123456
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    druid:
      initial-size: 5
      min-idle: 1
      max-active: 20
  servlet:
    multipart:
      max-file-size: 20MB
      enabled: true
      max-request-size: 20MB

logging:
  level:
    com.trust.xfyl.dao: debug

mybatis:
  mapper-locations: mapper/*.xml
  type-aliases-package: com.trust.xfyl.entity
  mybatis-config-file: mybatis-config.xml
  configuration.map-underscore-to-camel-case: false


imageurl:
  uploadImgUrl: /usr/home/uploadImage/


downloadurl:
  downloadImgUrl: /usr/home/downloadImg/

aliyun:
  api:
    accessKey: LTAI5tBDwYcXRACEzdXfvyMi
    secret: wTJRuVbKPFPwnEwhH2BvvNCtLGvSzV
    url: https://vision.console.aliyun.com/cn-shanghai/detail/imageprocess
    roleArn: acs:ram::1306143105217098:role/ramosstest
    policy: |
      {
        "Version": "1",
        "Statement": [
          {
            "Effect": "Allow",
            "Action": [
              "oss:PutObject",
              "oss:GetObject"
            ],
            "Resource": [
              "acs:oss:*:*:drt-oss-disk/src/*",
              "acs:oss:*:*:drt-oss-disk/dest/*"
            ]
          }
        ]
      }
    externalId: xfyl

swagger:
  basic:
    enable: true
    username: admin
    password: admin

