server:
  port: 8800
spring:
  application:
    name: chat-sample
  freemarker:
    cache: false
    charset: UTF-8
    suffix: .ftl
    enabled: true
    content-type: text/html
    template-loader-path: classpath:/templates/,classpath:/static/
  datasource:
    url: jdbc:mysql://121.43.138.108:3306/xfyl?serverTimezone=GMT%2b8&useSSL=false&characterEncoding=utf8&allowPublicKeyRetrieval=true&autoReconnect=true
    username: root
    password: Drt@123456
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 10
      maximum-pool-size: 20
      connection-test-query: SELECT 1
      connection-timeout: 30000
      validation-timeout: 30000

  servlet:
    multipart:
      max-file-size: 20MB
      enabled: true
      max-request-size: 20MB

logging:
  level:
    com.trust.xfyl.dao: debug

mybatis:
  mapper-locations: mapper/*.xml
  type-aliases-package: com.trust.xfyl.entity
  mybatis-config-file: mybatis-config.xml
  configuration.map-underscore-to-camel-case: false


imageurl:
  uploadImgUrl: /usr/home/uploadImage/


downloadurl:
  downloadImgUrl: /usr/home/downloadImg/

aliyun:
  api:
    url: https://vision.console.aliyun.com/cn-shanghai/detail/imageprocess
    roleArn: acs:ram::1306143105217098:role/ramosstest
    policy: |
      {
        "Version": "1",
        "Statement": [
          {
            "Effect": "Allow",
            "Action": [
              "oss:PutObject",
              "oss:GetObject"
            ],
            "Resource": [
              "acs:oss:*:*:drt-oss-disk/src/*",
              "acs:oss:*:*:drt-oss-disk/dest/*"
            ]
          }
        ]
      }
    externalId: xfyl

swagger:
  basic:
    enable: true
    username: admin
    password: admin
chat:
  llm:
    timeout: 60 #超时时间60秒
  security:
    refererWhitelist:
      - http://121.43.138.108:8800
      - http://121.43.138.108:80
      - http://121.43.138.108
  app:
    openTrace: true
    sessionMaxMessages: 50 #对话记录, 最多50条
    sessionTtl: 2          #对话缓存时间, 2小时
  cache:
    type: caffeine

